# Generated by Django 4.1.3 on 2024-05-23 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0003_yourmodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="Checkout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=15)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name="YourModel",
        ),
    ]
